BIN := build/server
CXX_SRC_DIR :=src
TARGET_DIR := build/targets
OBJ_DIR := build/objs

CC := gcc
CXX := g++
LD := g++

CFLAGS := -Wall -O3 -fPIC
CXXFLAGS := -std=c++11

include ../../builder/Makefile.executable